---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: web-rs
  labels: 
    app: nginx
spec: 
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      ver: "1.23"
  template:
    metadata: 
      name: web-pod
      labels:
        app: nginx
        ver: "1.23"
    spec: 
      containers:
        - name: nginx-cont
          image: nginx:1.23
          ports:
            - containerPort: 80   
              protocol: TCP 

---
apiVersion: v1
kind: Service
metadata: 
  name: web-svc
  labels: 
    app: nginx
spec: 
  selector:
    app: nginx
  type: LoadBalancer    
  ports:
    - name: web-port 
      port: 34599
      targetPort: 80   
    