---
apiVersion: v1
kind: Pod
metadata:
  name: policy
spec:
  Containers:
    - name: cont-policy
      image: alpine:3
      command:
        - sleep
        - "1"
  restartPolicy: Never

---
apiVersion: v1
kind: Pod
metadata: 
  name: poly
spec:
  containers:
    - name: cont-nopolicy
      image: alpine:3
      command:
        - sleep
        - "1"
      
